// <auto-generated />
using Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260117181446_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Api.Core.Entities.Hierarchy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parent_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<string>("Uuid")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("hierarchies");
                });

            modelBuilder.Entity("Api.Core.Entities.Picture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("CurationStatus")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "curation_status");

                    b.Property<string>("Extension")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "extension");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "file_name");

                    b.Property<string>("Index")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "index");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "location");

                    b.Property<long>("PHash")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "phash");

                    b.Property<int>("Sharpness")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "sharpness");

                    b.Property<int>("SubFolderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sub_folder_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.HasKey("Id");

                    b.HasIndex("CurationStatus");

                    b.HasIndex("PHash");

                    b.HasIndex("SubFolderId");

                    b.HasIndex("Type");

                    b.ToTable("picture");
                });

            modelBuilder.Entity("Api.Core.Entities.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LibraryPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("library_path");

                    b.Property<string>("ThemeMode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("theme_mode");

                    b.HasKey("Id");

                    b.ToTable("settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LibraryPath = "",
                            ThemeMode = "system"
                        });
                });

            modelBuilder.Entity("Api.Core.Entities.SubFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HierarchyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hierarchy_id");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("HierarchyId");

                    b.ToTable("sub_folders");
                });

            modelBuilder.Entity("Api.Core.Entities.Hierarchy", b =>
                {
                    b.HasOne("Api.Core.Entities.Hierarchy", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Api.Core.Entities.Picture", b =>
                {
                    b.HasOne("Api.Core.Entities.SubFolder", "SubFolder")
                        .WithMany("Pictures")
                        .HasForeignKey("SubFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubFolder");
                });

            modelBuilder.Entity("Api.Core.Entities.SubFolder", b =>
                {
                    b.HasOne("Api.Core.Entities.Hierarchy", "Hierarchy")
                        .WithMany("SubFolders")
                        .HasForeignKey("HierarchyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hierarchy");
                });

            modelBuilder.Entity("Api.Core.Entities.Hierarchy", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("SubFolders");
                });

            modelBuilder.Entity("Api.Core.Entities.SubFolder", b =>
                {
                    b.Navigation("Pictures");
                });
#pragma warning restore 612, 618
        }
    }
}
